; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = p4_16mb
src_dir = ./src

[common]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.36
framework = arduino

[env:p4_16mb]
extends = common
board = esp32-p4-evboard
board_build.psram = enabled
monitor_speed = 115200
lib_deps =
    lvgl/lvgl@^9.4.0
    lovyan03/LovyanGFX@^1.2.19
build_flags =
    -DLV_CONF_INCLUDE_SIMPLE=1
    -DLV_CONF_PATH=\"${PROJECT_SRC_DIR}/lv_conf.h\"
    -Isrc
    -DFORCE_LVGL_FULL_RENDER=0
    -DFORCE_LVGL_PARTIAL_RENDER=1
    -DLVGL_DRAW_BUF_LINES=80
    -DLVGL_FULL_SINGLE_BUF_SRAM=1
    -DLVGL_FULL_SRAM_ONLY=1
    -DCONFIG_LV_DRAW_BUF_ALIGN=64
    -DCONFIG_LV_ATTRIBUTE_MEM_ALIGN_SIZE=64
    -DUSE_LGFX_TOUCH=1
    -DTOUCH_I2C_PORT=1
    -DTOUCH_I2C_SDA=7
    -DTOUCH_I2C_SCL=8
    -DTOUCH_I2C_FREQ=100000
    -DTOUCH_RST=22
    -DTOUCH_INT=-1
    -DI2C_SCAN_ENABLE=1
;    -DTOUCH_I2C_ADDR=0x5D
;     -DTINYUSB_CDC_ENABLED=1
;     -DARDUINO_USB_CDC_ON_BOOT=1
