; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = p4_16mb
src_dir = ./src

[common]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.36
framework = arduino

[env:p4_16mb]
extends = common
board = esp32-p4-evboard
board_build.psram = enabled
monitor_speed = 115200
lib_deps =
    lvgl/lvgl@^9.4.0
    lovyan03/LovyanGFX@^1.2.19
build_flags =
    -DLV_CONF_INCLUDE_SIMPLE=1
    -DLV_CONF_PATH=\"${PROJECT_SRC_DIR}/lv_conf.h\"
    -Isrc
    -DLV_COLOR_DEPTH=16
    -DUSE_LGFX_TOUCH=1
