; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = p4_16mb
src_dir = ./src

[common]
platform = https://github.com/pioarduino/platform-espressif32.git#53.03.13+github
framework = arduino

[env:p4_16mb]
extends = common
board = esp32-p4-evboard
board_build.psram = enabled
monitor_speed = 115200
lib_deps =
    lvgl/lvgl@^9.4.0
    lovyan03/LovyanGFX@^1.2.19
build_flags =
    -DLV_CONF_INCLUDE_SIMPLE=1
    -DLV_CONF_PATH=\"${PROJECT_SRC_DIR}/lv_conf.h\"
    -Isrc
;     -DTINYUSB_CDC_ENABLED=1
;     -DARDUINO_USB_CDC_ON_BOOT=1
